project:
  type: website

website:
  title: "{{< fa user-ninja >}}ainsuasty"
  image: image/Insu.png
  favicon: image/favicon-32x32.png
  site-url: ainsuasty.com
  google-analytics: "UA-176122758-1" 
  repo-url: https://github.com/ainsu23/ainsuasty_quarto.git
  navbar:
    left: 
      - href: index.qmd
        text: "{{< fa home >}} Home"
      - href: rworld.qmd
        text: "{{< fa earth-americas >}} My R World"
    right: 
      - href: cv.html
        text: "{{< fa id-card >}} Vitae"
      
format:
  html:
   # theme: cosmo
    theme:
      light: flatly
      dark: darkly
    # css: styles.css
    toc: true



